import type { CuratedCategory, IconId, LibraryCategory } from './types';

export const DEFAULT_ICON_ID: IconId = 'BookOpen';

export const CURATED_CATEGORIES: CuratedCategory[] = [
  {
    id: 'study',
    label: 'Study',
    iconId: 'BookOpen',
    icons: [
      'BookOpen',
      'Notebook',
      'GraduationCap',
      'Pencil',
      'Library',
      'Calculator',
      'BookMarked',
      'PenLine',
      'Highlighter',
      'Microscope',
      'Brain',
      'Languages',
      'School',
      'ClipboardList',
      'FileText',
      'ScrollText',
    ],
  },
  {
    id: 'personal',
    label: 'Personal',
    iconId: 'Heart',
    icons: [
      'Heart',
      'Smile',
      'Coffee',
      'Gift',
      'Cake',
      'Flower',
      'Sparkles',
      'Star',
      'Home',
      'Camera',
      'Music',
      'Palette',
      'Bookmark',
      'Sun',
      'Moon',
      'Umbrella',
    ],
  },
  {
    id: 'work',
    label: 'Work',
    iconId: 'Briefcase',
    icons: [
      'Briefcase',
      'Calendar',
      'Clipboard',
      'Presentation',
      'Building2',
      'Laptop',
      'Mail',
      'Phone',
      'Users',
      'ChartBar',
      'Clock',
      'Target',
      'Handshake',
      'FileSpreadsheet',
      'Printer',
      'Globe',
    ],
  },
  {
    id: 'cute',
    label: 'Cute',
    iconId: 'Sparkles',
    icons: [
      'Sparkles',
      'Flower2',
      'Moon',
      'Cloud',
      'Sun',
      'Rainbow',
      'Cherry',
      'Cat',
      'Rabbit',
      'Butterfly',
      'Star',
      'HeartHandshake',
      'Candy',
      'IceCreamCone',
      'CloudSun',
      'Feather',
    ],
  },
  {
    id: 'productivity',
    label: 'Productivity',
    iconId: 'Timer',
    icons: [
      'Timer',
      'Target',
      'Rocket',
      'ChartColumn',
      'CheckSquare',
      'ListTodo',
      'Zap',
      'TrendingUp',
      'Flag',
      'AlarmClock',
      'Kanban',
      'Workflow',
      'Lightbulb',
      'CircleCheck',
      'CalendarCheck',
      'Gauge',
    ],
  },
];

export const LIBRARY_CATEGORIES: LibraryCategory[] = [
  { id: 'all', label: 'All icons', iconId: 'LayoutGrid' },
  { id: 'animals', label: 'Animals', iconId: 'Cat' },
  { id: 'nature', label: 'Nature', iconId: 'Leaf' },
  { id: 'food', label: 'Food/Drink', iconId: 'Coffee' },
  { id: 'objects', label: 'Objects', iconId: 'Box' },
  { id: 'ui', label: 'UI', iconId: 'LayoutDashboard' },
  { id: 'activities', label: 'Activities', iconId: 'Dumbbell' },
  { id: 'travel', label: 'Travel', iconId: 'Plane' },
  { id: 'people', label: 'People', iconId: 'Users' },
  { id: 'symbols', label: 'Symbols', iconId: 'Hash' },
  { id: 'files', label: 'Files', iconId: 'File' },
  { id: 'devices', label: 'Devices', iconId: 'Smartphone' },
  { id: 'weather', label: 'Weather', iconId: 'CloudSun' },
  { id: 'emotions', label: 'Emotions', iconId: 'Smile' },
  { id: 'others', label: 'Others', iconId: 'CircleEllipsis' },
];

export const RECENT_ICON_LIMIT = 8;

export const LIBRARY_PAGE_SIZE = 64;
