import type { ColorDefinition, PresetColorId } from './types';

export const DEFAULT_COLOR_ID: PresetColorId = 'lavender';

export const COLOR_PRESETS: Record<PresetColorId, ColorDefinition> = {
  rose: {
    id: 'rose',
    name: 'Rose',
    personality: 'Cute & Romantic',
    category: 'warm',
    icon: '🌹',
    light: { soft: '#FFE5EC', main: '#F3A3B5', strong: '#D56B85' },
    dark: { soft: '#4A2832', main: '#E59DB1', strong: '#FFD4DE' },
  },
  raspberry: {
    id: 'raspberry',
    name: 'Raspberry',
    personality: 'Energetic & Pop',
    category: 'warm',
    icon: '🍓',
    light: { soft: '#FBE0EA', main: '#EC89B0', strong: '#D43D74' },
    dark: { soft: '#4B2432', main: '#E480A8', strong: '#FFD3E4' },
  },
  coral: {
    id: 'coral',
    name: 'Coral',
    personality: 'Friendly & Cheerful',
    category: 'warm',
    icon: '🪸',
    light: { soft: '#FFE0DA', main: '#FFA79A', strong: '#E66A5C' },
    dark: { soft: '#4C2E2A', main: '#F0A294', strong: '#FFD4CD' },
  },
  peach: {
    id: 'peach',
    name: 'Peach',
    personality: 'Soft & Welcoming',
    category: 'warm',
    icon: '🍑',
    light: { soft: '#FFEAD8', main: '#FFC7A6', strong: '#D88A63' },
    dark: { soft: '#4C352B', main: '#E8B596', strong: '#FFDCC6' },
  },
  tangerine: {
    id: 'tangerine',
    name: 'Tangerine',
    personality: 'Bright & Active',
    category: 'warm',
    icon: '🍊',
    light: { soft: '#FFE3CC', main: '#FFB36B', strong: '#E67A18' },
    dark: { soft: '#4D331F', main: '#E5A76A', strong: '#FFD9B6' },
  },
  honey: {
    id: 'honey',
    name: 'Honey',
    personality: 'Warm & Cozy',
    category: 'warm',
    icon: '🍯',
    light: { soft: '#FFF2C9', main: '#F5CF73', strong: '#D89F17' },
    dark: { soft: '#4B4021', main: '#E5C26B', strong: '#FFE9A6' },
  },
  sage: {
    id: 'sage',
    name: 'Sage',
    personality: 'Vintage & Calm',
    category: 'nature',
    icon: '🌿',
    light: { soft: '#E8E8D9', main: '#C7CBA7', strong: '#7E8464' },
    dark: { soft: '#31332B', main: '#BEC39F', strong: '#E1E2D1' },
  },
  mint: {
    id: 'mint',
    name: 'Mint',
    personality: 'Fresh & Clean',
    category: 'nature',
    icon: '🌱',
    light: { soft: '#DDF7EE', main: '#9FE3CA', strong: '#4FA883' },
    dark: { soft: '#23372F', main: '#9BDDC6', strong: '#D9F4EA' },
  },
  moss: {
    id: 'moss',
    name: 'Moss',
    personality: 'Nature & Forest',
    category: 'nature',
    icon: '🌲',
    light: { soft: '#E3EAD8', main: '#AEBE8C', strong: '#6F8453' },
    dark: { soft: '#2E3427', main: '#A8B987', strong: '#DCE5D1' },
  },
  matcha: {
    id: 'matcha',
    name: 'Matcha',
    personality: 'Study & Productivity',
    category: 'nature',
    icon: '🍵',
    light: { soft: '#EEF7D8', main: '#CDE783', strong: '#8FB63A' },
    dark: { soft: '#2E371F', main: '#C7DE7C', strong: '#E8F3D0' },
  },
  sky: {
    id: 'sky',
    name: 'Sky',
    personality: 'Light & Airy',
    category: 'ocean',
    icon: '☁️',
    light: { soft: '#E3F3FF', main: '#A9D9FF', strong: '#5FA9E8' },
    dark: { soft: '#26384A', main: '#A4D2F8', strong: '#DCEEFF' },
  },
  cyan: {
    id: 'cyan',
    name: 'Cyan',
    personality: 'Ocean & Refreshing',
    category: 'ocean',
    icon: '🐋',
    light: { soft: '#DDF7FA', main: '#97E0E8', strong: '#3EA8B8' },
    dark: { soft: '#22373B', main: '#92D7DE', strong: '#D7F2F5' },
  },
  azure: {
    id: 'azure',
    name: 'Azure',
    personality: 'Adventure & Travel',
    category: 'ocean',
    icon: '✈️',
    light: { soft: '#DDEBFF', main: '#9DC2F7', strong: '#4E87E5' },
    dark: { soft: '#24324A', main: '#98BCF0', strong: '#D6E6FF' },
  },
  navy: {
    id: 'navy',
    name: 'Navy',
    personality: 'Professional & Focus',
    category: 'ocean',
    icon: '⚓',
    light: { soft: '#DCE3F0', main: '#9CB2D4', strong: '#45638A' },
    dark: { soft: '#202A39', main: '#97ACCD', strong: '#D4DDEA' },
  },
  lavender: {
    id: 'lavender',
    name: 'Lavender',
    personality: 'Dear Diary Signature',
    category: 'dreamy',
    icon: '💜',
    light: { soft: '#EFE8FF', main: '#C7B2FF', strong: '#8F6BE8' },
    dark: { soft: '#342A4D', main: '#C1ABF6', strong: '#E8E0FF' },
  },
  violet: {
    id: 'violet',
    name: 'Violet',
    personality: 'Fantasy & Magic',
    category: 'dreamy',
    icon: '🔮',
    light: { soft: '#E6E1FF', main: '#A995FF', strong: '#6E57E8' },
    dark: { soft: '#2F294A', main: '#A28EFF', strong: '#DCD6FF' },
  },
  plum: {
    id: 'plum',
    name: 'Plum',
    personality: 'Elegant & Royal',
    category: 'dreamy',
    icon: '👑',
    light: { soft: '#F2DCEB', main: '#C27BAA', strong: '#7D3E69' },
    dark: { soft: '#372636', main: '#BA75A2', strong: '#EAD7E4' },
  },
  lilac: {
    id: 'lilac',
    name: 'Lilac',
    personality: 'Dreamy & Moonlight',
    category: 'dreamy',
    icon: '🌙',
    light: { soft: '#F5EDFF', main: '#DCC8FF', strong: '#AE8BE8' },
    dark: { soft: '#3A3148', main: '#D5C0FF', strong: '#EEE5FF' },
  },
  ivory: {
    id: 'ivory',
    name: 'Ivory',
    personality: 'Minimal & Clean',
    category: 'neutral',
    icon: '🐱',
    light: { soft: '#FFFDF7', main: '#F0E9D7', strong: '#C8B89A' },
    dark: { soft: '#3A3832', main: '#E4DDCB', strong: '#FFFBEF' },
  },
  cocoa: {
    id: 'cocoa',
    name: 'Cocoa',
    personality: 'Warm & Cozy',
    category: 'neutral',
    icon: '☕',
    light: { soft: '#F0E1D5', main: '#D0AE8E', strong: '#8A6145' },
    dark: { soft: '#332821', main: '#C7A78A', strong: '#E9DACE' },
  },
};

export const PRESET_COLOR_IDS = Object.keys(COLOR_PRESETS) as PresetColorId[];

export const PRESET_CATEGORIES: {
  id: ColorDefinition['category'];
  label: string;
  colors: PresetColorId[];
}[] = [
  {
    id: 'warm',
    label: 'Warm',
    colors: ['rose', 'raspberry', 'coral', 'peach', 'tangerine', 'honey'],
  },
  {
    id: 'nature',
    label: 'Nature',
    colors: ['sage', 'mint', 'moss', 'matcha'],
  },
  {
    id: 'ocean',
    label: 'Ocean',
    colors: ['sky', 'cyan', 'azure', 'navy'],
  },
  {
    id: 'dreamy',
    label: 'Dreamy',
    colors: ['lavender', 'violet', 'plum', 'lilac'],
  },
  {
    id: 'neutral',
    label: 'Neutral',
    colors: ['ivory', 'cocoa'],
  },
];

export const RECENT_COLOR_LIMIT = 10;
